
HOST: http://www.yourdomain.com/

--- Sample API v2 ---
---
Welcome to the your sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
    Controller com.in3k8.javaconfig.controllers.GreeterController Resources
--

Method doGreet
POST /greet
< 200
> text/plain
